### PR TITLE
Small refactoring to ToGlyph.

### PR DESCRIPTION
**Pull request by tarrsalah**
Renaming some local variables, and making a better loop (using range).

### CODE REVIEW

**Comment by tarrsalah** [comment]
I'm not sure honestly , (I will do some benchmarking to prove that to myself).

**Comment by 01walid** [comment]
Yes, and I used the `length` of the old text as the capacity of the new one.
[From](https://blog.golang.org/slices#TOC_6.) the page you mentioned
> The Capacity field records how much space the underlying array actually has; it is the maximum value the Length can reach. Trying to grow the slice beyond its capacity will step beyond the limits of the array and will trigger a panic.

notice *the maximum value the Length can reach*
I guess we can clear confusion by using `cap(string)` instead of its length as the newText capacity...

**Comment by tarrsalah** [comment]
You are right, https://gist.github.com/tarrsalah/74e663fa3eb2e074a344
I think, just using  a `len(string)` is clear enough, the `len` and the `cap` of a  slice are usually the same.

**Comment by 01walid** [comment]
:+1: 
Then adjust  so I can merge this :)

**Pull request merged**
